github.com:
    users:
        kwphil:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kwphil
